spring:
  application:
    name: WebAuto

  datasource:
    url: jdbc:postgresql://localhost:1034/webauto
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

# JWT Configuration
jwt:
  secret: "dfasfsdflllfe90234324dfsa"
  expiration: 36000000

# Server
server:
  port: 8080
